import type { Grant, Product } from './types'

export const USER = {
  name: '桂*徽',
  phone: '199****1101',
  corp: '企业号 199****1101 已激活',
}

export const INITIAL_GRANTS: Grant[] = [
  { id: 'g1', title: '会员积分发放', amount: 5500, claimed: false },
  { id: 'g2', title: '补充积分发放', amount: 2000, claimed: false },
]

export const FOLLOW_UP_GRANT: Grant = {
  id: 'g3',
  title: '新增积分发放',
  amount: 800,
  claimed: false,
}

export const PRODUCTS: Product[] = [
  {
    id: 'gold',
    name: '通用金',
    subtitle: '虚拟类目商品',
    zone: 'benefit',
    cost: 1,
    validityDays: 90,
    stockLabel: '充足',
    benefitStatus: 'available',
    quota: 500,
    description: '兑换后可用于指定消费场景抵扣，具体以发放说明为准。',
    usage: '本商品按发放额度一次兑完剩余份数。兑换后不支持退回积分。',
  },
  {
    id: 'alipay',
    name: '支付宝通用券',
    subtitle: '虚拟类目商品',
    zone: 'benefit',
    cost: 1,
    validityDays: 90,
    stockLabel: '充足',
    benefitStatus: 'available',
    quota: 500,
    description: '兑换后将发放至绑定账户，可在支持的消费场景中抵扣使用。',
    usage: '本商品按发放额度一次兑完剩余份数。兑换后不支持退回积分。',
  },
  {
    id: 'alipay-plus',
    name: '支付宝通用券plus',
    subtitle: '虚拟类目商品',
    zone: 'benefit',
    cost: 1,
    validityDays: 90,
    stockLabel: '充足',
    benefitStatus: 'available',
    quota: 500,
    description: '兑换后将发放至绑定账户，可在支持的消费场景中抵扣使用。',
    usage: '本商品按发放额度一次兑完剩余份数。兑换后不支持退回积分。',
  },
  {
    id: 'wechat',
    name: '微信立减金',
    subtitle: '虚拟类目商品',
    zone: 'benefit',
    cost: 1,
    validityDays: 90,
    stockLabel: '充足',
    benefitStatus: 'available',
    quota: 200,
    description: '兑换后将发放至微信卡包，可在支持的商户中抵扣使用。',
    usage: '本商品按发放额度一次兑完剩余份数。兑换后不支持退回积分。',
  },
  {
    id: 'starbucks',
    name: '星巴克中杯兑换券',
    subtitle: '到店饮品兑换',
    zone: 'points',
    category: 'dining',
    cost: 99,
    validityDays: 90,
    stockLabel: '充足',
    description: '可兑换星巴克指定中杯饮品一杯，到店出示券码使用。',
    usage: '兑换后 90 天内有效，每单限用一张，不与其他优惠同享。',
  },
  {
    id: 'takeout',
    name: '外卖满减券',
    subtitle: '满 30 减 15',
    zone: 'points',
    category: 'dining',
    cost: 50,
    validityDays: 60,
    stockLabel: '充足',
    description: '外卖平台满减券，下单满 30 元可用，最高抵扣 15 元。',
    usage: '仅限外卖在线支付使用，过期自动作废。',
  },
  {
    id: 'hotpot',
    name: '火锅代金券',
    subtitle: '指定品牌通用',
    zone: 'points',
    category: 'dining',
    cost: 200,
    validityDays: 90,
    stockLabel: '充足',
    description: '指定火锅品牌门店代金券，到店消费可抵扣等额金额。',
    usage: '不可兑换现金，不找零，节假日通用。',
  },
  {
    id: 'movie',
    name: '电影票兑换券',
    subtitle: '热映影片可用',
    zone: 'points',
    category: 'life',
    cost: 120,
    validityDays: 90,
    stockLabel: '充足',
    ended: true,
    description: '可兑换指定影城电影票一张，支持热映影片在线选座。',
    usage: '部分特殊场次需补差价，以出票页说明为准。',
  },
  {
    id: 'video',
    name: '视频会员月卡',
    subtitle: '热门平台通用',
    zone: 'points',
    category: 'life',
    cost: 199,
    validityDays: 90,
    stockLabel: '充足',
    description: '兑换后开通 31 天视频会员权益，可观看会员影片与剧集。',
    usage: '兑换后需在有效期内完成开通，逾期作废。',
  },
  {
    id: 'market',
    name: '超市购物卡',
    subtitle: '线上线下可用',
    zone: 'points',
    category: 'life',
    cost: 500,
    validityDays: 180,
    stockLabel: '充足',
    description: '超市电子购物卡，可用于指定商超线上及线下消费。',
    usage: '不支持兑现，可分次使用，余额长期有效。',
  },
  {
    id: 'ride',
    name: '网约车代金券',
    subtitle: '出行即抵',
    zone: 'points',
    category: 'travel',
    cost: 100,
    validityDays: 60,
    stockLabel: '充足',
    description: '网约车行程代金券，支付车费时可直接抵扣。',
    usage: '每笔订单限用一张，不可与其他出行券叠加。',
  },
  {
    id: 'hotel',
    name: '酒店满减券',
    subtitle: '满 800 减 200',
    zone: 'points',
    category: 'travel',
    cost: 999,
    validityDays: 90,
    stockLabel: '充足',
    ended: true,
    description: '指定酒店预订满减券，订单满 800 元可减 200 元。',
    usage: '仅限预付订单，部分爆款房型除外。',
  },
  {
    id: 'digital',
    name: '数码配件优惠',
    subtitle: '限量精选',
    zone: 'points',
    category: 'life',
    cost: 2880,
    validityDays: 30,
    stockLabel: '充足',
    ended: true,
    description: '可抵扣指定数码配件订单金额，适合换新与配件加购。',
    usage: '数量有限，兑完即止，不支持拆分使用。',
  },
]

export const CATEGORIES: { id: 'all' | 'dining' | 'life' | 'travel'; label: string }[] = [
  { id: 'all', label: '全部' },
  { id: 'dining', label: '餐饮' },
  { id: 'life', label: '生活' },
  { id: 'travel', label: '出行' },
]

export const PRODUCT_TONES: Record<string, [string, string]> = {
  gold: ['#FFE08A', '#F5A623'],
  alipay: ['#5AB0FF', '#1677FF'],
  'alipay-plus': ['#7EC8FF', '#0A5CFF'],
  wechat: ['#62E08F', '#07C160'],
  starbucks: ['#4FB37A', '#006241'],
  takeout: ['#FFE566', '#FFD100'],
  hotpot: ['#FF8A7A', '#C41A1A'],
  movie: ['#FF8A8A', '#E23D2A'],
  video: ['#7EE8A4', '#00C853'],
  market: ['#5AB0FF', '#0071CE'],
  ride: ['#FFB347', '#FF6600'],
  hotel: ['#7EC8FF', '#287DFA'],
  digital: ['#FFB86B', '#FF6900'],
}
